package com.biaopu.droolsdemo.bean
import com.biaopu.droolsdemo.bean.People
import com.biaopu.droolsdemo.bean.Cat
dialect  "java"

rule "man"
    when
        $p : People(sex == 1 && drlType == "people")
    then
        System.out.println($p.getName() + "是男孩");
end

rule "cat"
    when
        $c : Cat(sex == 1 && $c.getName().equals("金"))
    then
        System.out.println($c.getName() + "是公的");

end
